const ActionsType = {
    RESTAURANT_LOADING: 'RESTAURANT_LOADING',
    RESTAURANT_SUCCESS: 'RESTAURANT_SUCCESS',
    RESTAURANT_ERROR: 'RESTAURANT_ERROR',
    PRODUCT_LOADING: 'PRODUCT_LOADING',
    PRODUCT_SUCCESS: 'PRODUCT_SUCCESS',
    PRODUCT_ERROR: 'PRODUCT_ERROR',
    CART_LOADING: 'CART_LOADING',
    CART_SUCCESS: 'CART_SUCCESS',
    CART_ERROR: 'CART_ERROR',
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_TO_ERROR: 'ADD_TO_ERROR',
    DELETE_CART: 'DELETE_CART',
    DELETE_ALL_CART: 'DELETE_ALL_CART',
    UPDATE_CART: 'UPDATE_CART',
    DELETE_FROM_CART: 'DELETE_FROM_CART',
}

export default ActionsType
